[Friday 12:20] Anurag Sharma
name: Run Test Classes
# deploy on push
on:
  push:
    paths:
      - force-app/**
 
jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Debug SFDX_AUTH_URL
        run: |
          echo "SFDX_AUTH_URL_PRODUCTION: ${{ secrets.SFDX_AUTH_URL }}"
      - name: Login To Org
        run: |
          sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: Debug Login Status
        run: |
          sfdx force:org:display